dist: trusty
sudo: required
language: java

env:
  global:
    - CATALOG_IMAGE_REPO=quay.io/tqvarnst/catalog-native
    - $INVENTORY_IMAGE_REPO=quay.io/tqvarnst/inventory-native
    - GRAALVM_HOME=$HOME/graalvm-ce-1.0.0-rc16

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
  - curl -LO https://github.com/oracle/graal/releases/download/vm-1.0.0-rc16/graalvm-ce-1.0.0-rc16-linux-amd64.tar.gz
  - tar -zxvf graalvm-ce-1.0.0-rc16-linux-amd64.tar.gz -C $HOME/

script:
  - mvn clean package -Pnative -DskipTests || exit
  - docker build -f event-store-service/src/main/docker/Dockerfile.native -t tqvarnst/coderland-event-store .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag tqvarnst/coderland-event-store:$TRAVIS_COMMIT quay.io/tqvarnst/coderland-event-store:$TAG
  - docker push quay.io/tqvarnst/coderland-event-store:$TAG